services:
  db:
    image: mariadb:11.8
    container_name: nc-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_DISABLE_UPGRADE_BACKUP: "1"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - nc-internal

  redis:
    image: redis:7-alpine
    container_name: nc-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nc-internal

  app:
    image: nextcloud:35-apache
    container_name: nc-app
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-8080}:80"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: redis

      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}

      PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT:-2G}
      APACHE_BODY_LIMIT: ${APACHE_BODY_LIMIT:-2147483648}

    volumes:
      - nc-html:/var/www/html
      - /srv/nextcloud-data/data:/var/www/html/data

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - nc-internal

  cron:
    image: nextcloud:35-apache
    container_name: nc-cron
    restart: unless-stopped
    entrypoint: /cron.sh
    volumes:
      - nc-html:/var/www/html
      - /srv/nextcloud-data/data:/var/www/html/data
    depends_on:
      - app
    networks:
      - nc-internal

volumes:
  db-data:
  nc-html:

networks:
  nc-internal:
    driver: bridge